`timescale 1ns / 1ps
module tb_TimerCounter();

    logic          clk     ;
    logic          rst_n   ;
    logic          cnt_en  ;
    logic          intr_en ;
    logic [31:0]   psc     ;
    logic [31:0]   arr     ;
    logic [31:0]   i_cnt    ;
    logic [31:0]   o_cnt    ;
    logic          intr     ;
    logic          cnt_valid;

    TimerCounter dut(.*);

    task TIM_SetPSC(logic [31:0] prescale);
        psc = prescale;
    endtask 

    task TIM_SetARR(logic [31:0] autoReload);
        arr = autoReload;
    endtask

    task TIM_EnTimer();
        cnt_en = 1'b1;
    endtask 

    task TIM_DisTimer();
        cnt_en = 1'b0;
    endtask 

    task TIM_EnIntr();
        intr_en = 1'b1;
    endtask 
    
    task TIM_DisIntr();
        intr_en = 1'b0;
    endtask 

    task TIM_SetCNT(logic [31:0] CNT);
        i_cnt = CNT;
        cnt_valid <= 1'b1;
        @(posedge clk);
        cnt_valid <= 1'b0;
    endtask


    always #5 clk = ~clk;

    initial begin
        clk       = 0;
        rst_n     = 0;
        i_cnt     = 0;
        cnt_valid = 0;
        repeat(3) @(posedge clk);
        rst_n   = 1;
        @(posedge clk);

        TIM_SetPSC(100-1); // output 1MHz
        TIM_SetARR(1000-1);// TimerCounter 0~999
        TIM_EnTimer(); 
        TIM_DisIntr();
        wait(o_cnt == 999);
        @(posedge clk);
        wait(o_cnt == 0);
        @(posedge clk);
        TIM_EnIntr();
        wait(o_cnt == 999);
        @(posedge clk);
        wait(o_cnt == 100);
        @(posedge clk);
        TIM_SetCNT(10);
        @(posedge clk);
        wait(o_cnt == 0);
        @(posedge clk);

        #1000;
        #1000;
        #10000;
        $stop;        
    end

endmodule

